"project_id_env": "CROWDIN_OPEN_PROJECT_ID"
"api_token_env": "CROWDIN_API_SECRET"
"pull_request_title": "chore(l10n): Translations updates"
"files": [
  {
    "source": "/languages/fake-plugin.pot",
    "translation": "/languages/%locale_with_underscore%.po",
    "languages_mapping": {
      "locale_with_underscore": {
        "de-DE": "de_DE",
        "es-ES": "es_ES",
        "fr-FR": "fr_FR",
        "gl-ES": "gl_ES",
        "nb-NO": "nb_NO",
        "it-IT": "it_IT",
        "ka-GE": "ka_GE",
        "ru-RU": "ru_RU",
        "ta-LK": "ta_LK",
        "hr": "hr_HR"
      }
    }
  }
]
