name: Pressbooks auto merge
on:
  pull_request_target:
    types: [ opened ]

jobs:
  automerge:
    if: github.actor == 'pressbooks-ops' || github.actor == 'transifex-integration' || github.actor == 'dependabot[bot]'
    uses: pressbooks/composer-autoupdate-bedrock/.github/workflows/auto-merge.yml@main
    with:
      pr_title_pattern: '^(chore(l10n|i18n)?:)'
    secrets: inherit
