name: Automerge translations ✨
on:
  pull_request_target:
    types: [ opened ]

jobs:
  automerge:
    if: github.actor == 'pressbooks-ops' || github.actor == 'transifex-integration[bot]' || github.actor == 'dependabot[bot]'
    uses: pressbooks/reusable-workflows/.github/workflows/auto-merge.yml@test-tag-release
    with:
      pr_title_pattern: '^(chore\((l10n|i18n)\):)'
    secrets: inherit
