name: Run Standards & Tests

on:
  push:
    branches: [ dev, main ]

jobs:
  trigger_bedrock_updates:
    if: github.ref == 'refs/heads/dev'
    uses: actions/composer-autoupdate-bedrock@v1.1
    with:
      triggered-by: ${{ github.repository }}
