name: Run Standards & Tests

on:
  push:
    branches: [ dev, main ]

jobs:
  trigger_bedrock_updates:
    steps:
      if: github.ref == 'refs/heads/dev'
      uses: pressbooks/composer-autoupdate-bedrock/.github/workflows/trigger-update.yml@main
      secrets: inherit
