name: Run Standards & Tests

on:
  push:
    branches: [ dev, main ]

jobs:
  trigger_bedrock_updates:
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Trigger Bedrock Updates
        uses: pressbooks/composer-autoupdate-bedrock@v1.1
        with:
          triggered-by: ${{ github.repository }}
