name: Run Standards & Tests

on:
  push:
    branches: [ dev, production ]

jobs:
  trigger_bedrock_updates:
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/production'
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Trigger Bedrock Updates
        uses: pressbooks/composer-autoupdate-bedrock@chore/update-bedrocks-with-aws-queue-and-lambda-function
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SNS_ARN_DEV: ${{ secrets.AWS_SNS_ARN_DEV }}
          AWS_SNS_ARN_STAGING: ${{ secrets.AWS_SNS_ARN_STAGING }}
          INPUT_TRIGGERED_BY: ${{ github.repository }}
          INPUT_BRANCH: ${{ github.ref }}
