name: Prepare Release

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    uses: pressbooks/reusable-workflows/.github/workflows/prepare-release.yml@dev
    with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
    secrets: inherit
