name: Update Translation Files 🌐

on:
  pull_request:
    branches: [dev]
    paths:
      - "**.php"
      - "**.js"
      - "languages/*.po"
  workflow_dispatch:

jobs:
  update-translation-files:
    uses: pressbooks/reusable-workflows/.github/workflows/update-translations.yml@update
    secrets: inherit
    with:
      domain: 'pressbooks-fake-plugin'
      slug: 'pressbooks-fake-plugin'
      package_name: 'Pressbooks Fake Plugin'
      headers: '{"Report-Msgid-Bugs-To": "https://github.com/pressbooks/fake-plugin/issues"}'
      pull_request_number: ${{ github.event.pull_request.number }}
